import { webhookStore } from './WebhookStore';
import { geminiService } from './GeminiService';
import nodemailer from 'nodemailer';

export class WebhookService {
  async sendNotification(connName: string, text: string, overrideUrl?: string): Promise<boolean> {
    const config = await webhookStore.getWebhook(connName);
    const targetUrl = overrideUrl || (config ? config.url : '');
    if (!targetUrl) return false;

    // Standard payload for Discord, Slack, and generic webhooks
    const payload = {
      text: text, // Slack & Teams format
      content: text // Discord format
    };

    try {
      const response = await fetch(targetUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      return true;
    } catch (err: any) {
      console.error('[WebhookService] Failed to send outbound webhook:', err.message || err);
      throw new Error('Outbound webhook call failed: ' + (err.message || err));
    }
  }

  async sendEmailNotification(
    connName: string,
    text: string,
    overrideEmail?: string,
    overrideSmtpHost?: string,
    overrideSmtpPort?: number,
    overrideSmtpSecure?: number,
    overrideSmtpUser?: string,
    overrideSmtpPass?: string,
    overrideSmtpSender?: string
  ): Promise<boolean> {
    const config = await webhookStore.getWebhook(connName);
    const targetEmail = overrideEmail || (config ? (config as any).email : '');
    if (!targetEmail) return false;

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    const emails = targetEmail.split(',').map((e: string) => e.trim());
    for (const email of emails) {
      if (email && !emailRegex.test(email)) {
        throw new Error(`Invalid email target address format: ${email}`);
      }
    }

    const host = overrideSmtpHost !== undefined ? overrideSmtpHost : (config ? (config as any).smtpHost : '');
    const port = overrideSmtpPort !== undefined ? overrideSmtpPort : (config ? (config as any).smtpPort : 587);
    const secure = overrideSmtpSecure !== undefined ? overrideSmtpSecure : (config ? (config as any).smtpSecure : 0);
    const user = overrideSmtpUser !== undefined ? overrideSmtpUser : (config ? (config as any).smtpUser : '');
    const pass = overrideSmtpPass !== undefined ? overrideSmtpPass : (config ? (config as any).smtpPass : '');
    const sender = overrideSmtpSender !== undefined ? overrideSmtpSender : (config ? (config as any).smtpSender : '');

    // Convert markdown to simple HTML for email client compatibility
    const htmlBody = text
      .replace(/\n/g, '<br>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/### (.*?)(<br>|$)/g, '<h3>$1</h3>')
      .replace(/`([^`]+)`/g, '<code>$1</code>');

    if (host) {
      console.log(`[WebhookService] Attempting REAL SMTP dispatch via ${host}:${port} (Secure: ${secure}) to [${emails.join(', ')}]`);
      
      const transporter = nodemailer.createTransport({
        host: host,
        port: port,
        secure: secure === 1,
        auth: user && pass ? {
          user: user,
          pass: pass
        } : undefined,
        tls: {
          rejectUnauthorized: false // bypass potential self-signed certificate issues in internal dev/SRE environments
        }
      });

      await transporter.sendMail({
        from: sender || user || 'VibeMongo Alerting <alerts@vibemongo.local>',
        to: emails.join(', '),
        subject: `🚨 [VibeMongo Alert] SRE Incident detected on connection: ${connName}`,
        text: text,
        html: `
          <div style="font-family: sans-serif; padding: 20px; line-height: 1.6; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px;">
            <h2 style="color: #d9534f; margin-top: 0;">🚨 VibeMongo SRE Autonomous Incident Report</h2>
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;" />
            <div>${htmlBody}</div>
            <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
            <p style="font-size: 11px; color: #999; margin-bottom: 0;">
              This is an automated diagnostic email generated by VibeMongo SRE Guardian sentinel for <strong>${connName}</strong> connection.
            </p>
          </div>
        `
      });
      console.log(`[WebhookService] REAL SMTP dispatch successful!`);
      return true;
    } else {
      console.log(`[WebhookService] No SMTP Host configured. Simulating SMTP dispatch to [${emails.join(', ')}] with SRE Alert for connection ${connName}`);
      // Simulate SMTP network latency
      await new Promise((resolve) => setTimeout(resolve, 800));
      return true;
    }
  }

  async triggerTestWebhook(
    connName: string,
    overrideUrl?: string,
    overrideEmail?: string,
    overrideSmtpHost?: string,
    overrideSmtpPort?: number,
    overrideSmtpSecure?: number,
    overrideSmtpUser?: string,
    overrideSmtpPass?: string,
    overrideSmtpSender?: string
  ): Promise<{ markdown: string; webhookSent: boolean; emailSent: boolean; targetEmail?: string; targetUrl?: string }> {
    const config = await webhookStore.getWebhook(connName);
    const targetUrl = overrideUrl || (config ? config.url : '');
    const targetEmail = overrideEmail || (config ? (config as any).email : '');
    
    if (!targetUrl && !targetEmail) {
      throw new Error('Either Webhook URL or Email Address must be configured.');
    }

    const systemPrompt = `You are a state-of-the-art MongoDB SRE Autonomous Sentinel.
Generate a gorgeous, high-fidelity mock SRE Incident report in Markdown format.
Focus on an anomaly event like a "COLLSCAN Slow Query Spike" or "Memory Resource exhaustion" for a MongoDB connection named "${connName}".

Rules for the incident report:
- Write it in a highly professional, alert style (with emojis like 🚨, ⚠️, 🛠️, 📊).
- Structure it with sections:
  1. Incident Summary (Status: DEGRADED, Health Score: e.g., 72%, Affected connection, P99 latency spike).
  2. Telemetry Root Cause Analysis (AI diagnostic explaining that a large collection-scan of 2,400 documents was executed on "orders" because of a missing compound index).
  3. Actionable Remediation (The SRE recommended compound index to create).
- Make sure to use bolding and tables where appropriate to look incredibly premium.
- Output ONLY the formatted markdown incident report. Do not add markdown code blocks (\`\`\`) around it. Just pure markdown.
`;

    const userPrompt = `Synthesize a premium mock SRE incident alert for connection "${connName}".`;
    
    let markdownReport = '';
    try {
      markdownReport = await geminiService.generateContent(userPrompt, systemPrompt);
    } catch (e) {
      // Local fallback in case Gemini fails
      markdownReport = `🚨 **VibeMongo Autopilot Incident Report**

**System Status:** ⚠️ DEGRADED (Health Score: 78%)
**Affected Connection:** \`${connName}\`

### 📊 Telemetry Metrics
- **P99 Latency:** \`1.48s\` (Normal: <0.20s)
- **Active Alerts:** \`3 slow query events detected\`
- **Memory Resident:** \`812 MB\` (Peak resident usage reached)

### 🛠️ AI Root Cause Diagnostics
AI evaluated active Phoenix trace telemetry logs and detected a COLLSCAN query matching \`POST /api/${connName}/orders/find\`. Large table-scans (1,850 documents examined) are bypassing existing active single-key indexes.

### 💡 Remediation Recommendation
> Recommended creating the following compound index:
\`\`\`javascript
db.orders.createIndex({ status: 1, createdAt: -1 }, { background: true })
\`\`\`
This will eliminate the COLLSCAN index-miss and reduce P99 query latency back to <5ms.`;
    }

    let webhookSent = false;
    let emailSent = false;

    if (targetUrl) {
      await this.sendNotification(connName, markdownReport, targetUrl);
      webhookSent = true;
    }

    if (targetEmail) {
      await this.sendEmailNotification(
        connName,
        markdownReport,
        targetEmail,
        overrideSmtpHost,
        overrideSmtpPort,
        overrideSmtpSecure,
        overrideSmtpUser,
        overrideSmtpPass,
        overrideSmtpSender
      );
      emailSent = true;
    }

    return {
      markdown: markdownReport,
      webhookSent,
      emailSent,
      targetUrl,
      targetEmail
    };
  }
}

export const webhookService = new WebhookService();
